### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by Rakesh9100** [srijoy-paul/University-website#5]

**Comment by kartiksaxena532** [comment]
hi sir i can work on this issue pls assign me this task

**Comment by srijoy-paul** [comment]
@kartiksaxena532 Sure assigning you
Just write a simple readme for the project
You can take reference: https://github.com/EddieHubCommunity/hacktoberfest-practice/blob/main/README.md

**Comment by Rakesh9100** [comment]
@srijoy-paul I have opened this issue so kindly assign me

**Comment by srijoy-paul** [comment]
@Rakesh9100 Sure go ahead

**Comment by Rakesh9100** [comment]
> @Rakesh9100 Sure go ahead

Unassign kartiksaxena and review the PR !!! @srijoy-paul
