### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Rakesh9100** [srijoy-paul/University-website#6]
Will add a favicon to make the website better under Hacktoberfest.

**Comment by kartiksaxena532** [comment]
hi sir i can add favicon to the website pls assign me this task

**Comment by srijoy-paul** [comment]
@Rakesh9100 You want to work on this?

**Comment by Rakesh9100** [comment]
> @Rakesh9100 You want to work on this?

Yes of course.

**Comment by srijoy-paul** [comment]
@Rakesh9100 Okay assigning you the task
