### ISSUE TITLE
Add Pre-loader to each page

### ISSUE THREAD

**Issue by srijoy-paul** [srijoy-paul/University-website#9]
Add a pre-loader to each page, and it's design should align with the website. And the main page should be visible once it has completely loaded.
Can use this as a reference : 
1. https://youtu.be/xuA83OYTE7I
2. https://youtu.be/Yf5d_Zx3AaI

**Comment by ighmaZ** [comment]
would love to work on this

**Comment by ighmaZ** [comment]
@srijoy-paul i would love to work on this

**Comment by srijoy-paul** [comment]
@ighmaZ Sure go ahead, assigning you the task
